### ISSUE TITLE
Client throws fatal errors for lightning wand but doesn't actually crash in v1.71

### ISSUE THREAD

**Issue by kreezxil** [cyanobacterium/DrCyanosWonderfulWands#7] opened 2015-07-22 17:22 UTC
```
[12:16:14] [Client thread/FATAL] [FML]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.ClassCastException: cyano.wonderfulwands.projectiles.EntityWandLightningBolt cannot be cast to net.minecraft.entity.EntityLivingBase
java.util.concurrent.ExecutionException: java.lang.ClassCastException: cyano.wonderfulwands.projectiles.EntityWandLightningBolt cannot be cast to net.minecraft.entity.EntityLivingBase
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1018) [bsu.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345) [bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.ClassCastException: cyano.wonderfulwands.projectiles.EntityWandLightningBolt cannot be cast to net.minecraft.entity.EntityLivingBase
	at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:817) ~[cee.class:?]
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_180721_a(SourceFile:109) ~[io.class:?]
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15) ~[io.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
	... 17 more
```

https://paste.ee/p/bQ08r

**Comment by cyanobacterium** [comment] 2015-07-30 22:12
Sorry for the long delay (had no internet for over a week). I'll look into it.

**Comment by cyanobacterium** [comment] 2015-07-30 23:21
If I identified the problem correctly, then the fix is in version 1.7.2

**Closed by cyanobacterium** 2015-07-30 23:21 UTC

**Comment by kreezxil** [comment] 2015-08-08 20:03
It is still doing it in version 1.7.4

```
[14:58:09] [Client thread/FATAL] [FML]: Exception caught executing FutureTask: java.util.concurrent.ExecutionException: java.lang.ClassCastException: cyano.wonderfulwands.projectiles.EntityWandLightningBolt cannot be cast to net.minecraft.entity.EntityLivingBase
java.util.concurrent.ExecutionException: java.lang.ClassCastException: cyano.wonderfulwands.projectiles.EntityWandLightningBolt cannot be cast to net.minecraft.entity.EntityLivingBase
	at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_51]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:715) [FMLCommonHandler.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1019) [bsu.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:345) [bsu.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:120) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:394) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
Caused by: java.lang.ClassCastException: cyano.wonderfulwands.projectiles.EntityWandLightningBolt cannot be cast to net.minecraft.entity.EntityLivingBase
	at net.minecraft.client.network.NetHandlerPlayClient.func_147281_a(NetHandlerPlayClient.java:817) ~[cee.class:?]
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_180721_a(SourceFile:109) ~[io.class:?]
	at net.minecraft.network.play.server.S0FPacketSpawnMob.func_148833_a(SourceFile:15) ~[io.class:?]
	at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[ih.class:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_51]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_51]
	at net.minecraftforge.fml.common.FMLCommonHandler.callFuture(FMLCommonHandler.java:714) ~[FMLCommonHandler.class:?]
	... 17 more
```

**Comment by cyanobacterium** [comment] 2015-08-08 21:16
I removed all possible class cast conflicts in the 1.7.2 update. Something is trying to spawn the lightning bolt entity as a mob, but it is plain entity, not a living entity. This might be a problem caused by another mod.

**Comment by kreezxil** [comment] 2015-08-08 21:20
Ok,I think I have two other mod that do something with lightning bolts. Thanks for helping to maps it down.

-----Original Message-----

**Comment by cyanobacterium** [comment] 2015-08-08 21:24
I don't think that it is lightning bolt specific because the wand lightning bolt is not the same as the vanilla lightning bolt (EntityWandLightningBolt  extends Entity). If you have any mods that modify mob spawning behavior, one of them may be using the spawn entity hook without checking whether the spawned entity is really a mob.

**Comment by kreezxil** [comment] 2015-08-08 21:27
I have lots of mods modifying the behavior of the mob spawning. :(
